### ISSUE TITLE
When adding a workspace we are getting an unexpected token in  JSON ERROR

### ISSUE THREAD

**Issue by Justin-Stockton** [Dave89rr/Stakr#19]
![image](https://user-images.githubusercontent.com/99220434/180610510-2f527bcd-8046-4387-ac4b-c98dd5b5b2cb.png)

**Comment by Dave89rr** [comment]
Error traces back to workspaces.js component in line that calls the workspace state `const data = dispatch(thunkCreateWorkspace(workspace));`

Unsure if the error is in how the thunk is called or an error in the state file

**Comment by Dave89rr** [comment]
Fixed in 11f187baffe09c800a3cd0d21fb693310fc49c6e
