### ISSUE TITLE
WS Creation error.

### ISSUE THREAD

**Issue by Justin-Stockton** [Dave89rr/Stakr#20]
When creating a workspace you can currently not name your WS and it will just set the name to be an empty string. We need validation on the front end to not allow this.

![image](https://user-images.githubusercontent.com/99220434/180657565-c9d43285-ec3d-4a42-8998-0caff395ea2d.png)

**Comment by Dave89rr** [comment]
Fixed in 2f2f00212a6d24f8f1a231919398de7d8cfdf711
