### ISSUE TITLE
Card Creation not updating Redux State

### ISSUE THREAD

**Issue by Dave89rr** [Dave89rr/Stakr#28]
Upon new card creation, no page re-render occurs.

Recreate Steps: 
Upon clicking (or hitting enter) to create a new card, the form disappears as if nothing was created and without warnings. 
However, refreshing the page will show that there are the newly created cards

**Comment by brandonflores647** [comment]
Fixed in 1fb9d9409c8f27cb88b651078b3de21969e6c89a
