### ISSUE TITLE
UserHomePage.js Sidebar loads incorrectly

### ISSUE THREAD

**Issue by Dave89rr** [Dave89rr/Stakr#39]
## Certain boards appear invisible until you hover over them

![image](https://user-images.githubusercontent.com/6596778/181918261-ff17ef7a-cee2-46d2-aee0-c12adc5d00da.png)

![New Project (1)](https://user-images.githubusercontent.com/6596778/181918484-903b0106-7b8f-4955-84f7-14624d248415.png)

**Comment by Dave89rr** [comment]
This is a non-issue. This only happens when the board's color is stored incorrectly in the database. (i.e. "blue" vs "Blue"

**Comment by Dave89rr** [comment]
After fixing in database
![image](https://user-images.githubusercontent.com/6596778/181937208-c78eacb0-ddc6-4483-a16f-f6faf2f340bc.png)

**Comment by Dave89rr** [comment]
Properly created boards are still not displaying

**Comment by brandonflores647** [comment]
fixed 49b5d6d9f723f949df0d632d9e7d9d2420d5238d
