### ISSUE TITLE
App is not deploying to Heroku

### ISSUE THREAD

**Issue by Dave89rr** [Dave89rr/Stakr#5]
When attempting to auto-deploy the following error is raised:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Stakr/Stakr/Pipfile.lock'`

**Comment by Justin-Stockton** [comment]
The application is now deploying to Heroku but is encountering an error upon loading.

**Comment by Dave89rr** [comment]
# Update:

Original issue has been addressed by editing the mail.yml file and tweaking the `Dockerfile`.

Both of the new issues during deployment are app name related.

## New problem 1: 

We're getting an error in our database:
![image](https://user-images.githubusercontent.com/6596778/180609013-149afbdd-7d91-4ad1-9738-35b88fc48fc2.png)


## New Problem 2:

During deployment gunicorn is failing to find the app. Our `CMD gunicorn app:app` line might need tweaking:

![image](https://user-images.githubusercontent.com/6596778/180608937-238bcce0-f762-49ac-b6c0-998339158380.png)

**Comment by Dave89rr** [comment]
Fixed by Justin in 6dd6c1cc2152bd265a71101467611da41d44de4f.

We gave up with being picky about our file structure.
