### ISSUE TITLE
Plus Icon

### ISSUE THREAD

**Issue by Dave89rr** [Dave89rr/Stakr#51]
## Issue:

If a workspace is ever found to have no stacks in it across any board, the + icon to add a new stack grows in size.

![image](https://user-images.githubusercontent.com/6596778/182052407-f9103b46-bfd4-4750-96dd-768ec053ade6.png)

**Comment by brandonflores647** [comment]
fixed c3bfb2831ce9cbb714e77edae27988df355fd761
